version: '3.8'

services:
  openlist-cli:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: openlist-cli
    image: openlist-cli-web:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=production
